apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: myingress
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Values.ingress.serviceName }}
            port:
              number: {{ .Values.ingress.servicePort }}