apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: techtrek
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.databaseUrl | quote }}
  SECRET_KEY: {{ .Values.secretKey | quote }}