/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(citizen)'}/track` | `/track`; params?: Router.UnknownInputParams; } | { pathname: `${'/(clerk)'}/case-detail` | `/case-detail`; params?: Router.UnknownInputParams; } | { pathname: `${'/(clerk)'}/cases` | `/cases`; params?: Router.UnknownInputParams; } | { pathname: `${'/(clerk)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(clerk)'}/new-case` | `/new-case`; params?: Router.UnknownInputParams; } | { pathname: `${'/(clerk)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/api/client`; params?: Router.UnknownInputParams; } | { pathname: `/api/services`; params?: Router.UnknownInputParams; } | { pathname: `/components`; params?: Router.UnknownInputParams; } | { pathname: `/constants/design`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useAuthStore`; params?: Router.UnknownInputParams; } | { pathname: `/types`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(citizen)'}/track` | `/track`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(clerk)'}/case-detail` | `/case-detail`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(clerk)'}/cases` | `/cases`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(clerk)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(clerk)'}/new-case` | `/new-case`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(clerk)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/api/client`; params?: Router.UnknownOutputParams; } | { pathname: `/api/services`; params?: Router.UnknownOutputParams; } | { pathname: `/components`; params?: Router.UnknownOutputParams; } | { pathname: `/constants/design`; params?: Router.UnknownOutputParams; } | { pathname: `/hooks/useAuthStore`; params?: Router.UnknownOutputParams; } | { pathname: `/types`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(citizen)'}/track${`?${string}` | `#${string}` | ''}` | `/track${`?${string}` | `#${string}` | ''}` | `${'/(clerk)'}/case-detail${`?${string}` | `#${string}` | ''}` | `/case-detail${`?${string}` | `#${string}` | ''}` | `${'/(clerk)'}/cases${`?${string}` | `#${string}` | ''}` | `/cases${`?${string}` | `#${string}` | ''}` | `${'/(clerk)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(clerk)'}/new-case${`?${string}` | `#${string}` | ''}` | `/new-case${`?${string}` | `#${string}` | ''}` | `${'/(clerk)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/api/client${`?${string}` | `#${string}` | ''}` | `/api/services${`?${string}` | `#${string}` | ''}` | `/components${`?${string}` | `#${string}` | ''}` | `/constants/design${`?${string}` | `#${string}` | ''}` | `/hooks/useAuthStore${`?${string}` | `#${string}` | ''}` | `/types${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(citizen)'}/track` | `/track`; params?: Router.UnknownInputParams; } | { pathname: `${'/(clerk)'}/case-detail` | `/case-detail`; params?: Router.UnknownInputParams; } | { pathname: `${'/(clerk)'}/cases` | `/cases`; params?: Router.UnknownInputParams; } | { pathname: `${'/(clerk)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(clerk)'}/new-case` | `/new-case`; params?: Router.UnknownInputParams; } | { pathname: `${'/(clerk)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/api/client`; params?: Router.UnknownInputParams; } | { pathname: `/api/services`; params?: Router.UnknownInputParams; } | { pathname: `/components`; params?: Router.UnknownInputParams; } | { pathname: `/constants/design`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useAuthStore`; params?: Router.UnknownInputParams; } | { pathname: `/types`; params?: Router.UnknownInputParams; };
    }
  }
}
